name: "Deploy Docker image via SSH & restart server on PM2"

inputs:
  API_DEPLOY_HOST:
    description: "The host of the server to deploy to"
    required: true
  API_DEPLOY_USERNAME:
    description: "The username for SSH connection"
    required: true
  API_DEPLOY_SSH_KEY:
    description: "The SSH private key for authentication"
    required: true
  API_DEPLOY_SSH_PASSPHRASE:
    description: "The passphrase for the SSH private key"
    required: true
  API_DEPLOY_PORT:
    description: "The port for SSH connection"
    default: "22"
  DOCKERHUB_USERNAME:
    description: "Docker Hub username for authentication (optional)"
    required: true
  DOCKERHUB_SECRET:
    description: "Docker Hub password for authentication (optional)"
    required: true
  DOCKER_IMAGE_NAME:
    description: "The full name of the Docker image"
    required: true
    default: ${{ github.repository }}
  DOCKER_IMAGE_TAG:
    description: "The tag of the Docker image to deploy (e.g., latest or commit SHA)"
    default: "latest"
  DOCKER_HOST_PORT:
    description: "The host port to map for the Docker container"
    required: true
  DOCKER_CONTAINER_PORT:
    description: "The port the application listens on inside the Docker container"
    required: true
    default: "3000"
  MAIL_CONTACT_ADDRESS:
    description: "Email address for contact"
    required: true
  MAIL_HOST:
    description: "SMTP host for email"
    required: true
  MAIL_PASS:
    description: "SMTP password for email"
    required: true
  MAIL_PORT:
    description: "SMTP port for email"
    required: true
  MAIL_SECURE:
    description: "SMTP secure connection (true/false)"
    required: true
  MAIL_USER:
    description: "SMTP user for email"
    required: true
  NODE_ENV:
    description: "Node environment, staging or production"
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy Docker Image and Update Server
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ inputs.API_DEPLOY_HOST }}
        username: ${{ inputs.API_DEPLOY_USERNAME }}
        key: ${{ inputs.API_DEPLOY_SSH_KEY }}
        passphrase: ${{ inputs.API_DEPLOY_SSH_PASSPHRASE }}
        port: ${{ inputs.API_DEPLOY_PORT }}
        script: |
          set -e
          # Load NVM. Assuming NVM is installed for the user and the NVM_DIR is ~/.nvm
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion (optional)

          DOCKER_CONTAINER_NAME="${{ github.repository }}_${{ inputs.NODE_ENV }}"
          docker login -u "${{ inputs.DOCKERHUB_USERNAME }}" --password-stdin <<< "${{ inputs.DOCKERHUB_SECRET }}"

          FULL_IMAGE="${{ inputs.DOCKER_IMAGE_NAME }}:${{ inputs.DOCKER_IMAGE_TAG }}"
          echo "Pulling Docker image: $FULL_IMAGE"
          docker pull "$FULL_IMAGE"

          echo "Stopping and removing existing container if it exists..."
          docker stop "$DOCKER_CONTAINER_NAME" || true
          docker rm "$DOCKER_CONTAINER_NAME" || true

          # Stop and delete existing PM2 process (if running)
          echo "Stopping and deleting existing PM2 process if it exists..."
          pm2 stop "$DOCKER_CONTAINER_NAME"  || true
          pm2 delete "$DOCKER_CONTAINER_NAME" || true

          # Construct environment variables string for docker run
          ENV_VARS_STRING=""
          ENV_VARS_STRING+=" -e MAIL_CONTACT_ADDRESS=\"${{ inputs.MAIL_CONTACT_ADDRESS }}\""
          ENV_VARS_STRING+=" -e MAIL_HOST=\"${{ inputs.MAIL_HOST }}\""
          ENV_VARS_STRING+=" -e MAIL_PASS=\"${{ inputs.MAIL_PASS }}\""
          ENV_VARS_STRING+=" -e MAIL_PORT=\"${{ inputs.MAIL_PORT }}\""
          ENV_VARS_STRING+=" -e MAIL_SECURE=\"${{ inputs.MAIL_SECURE }}\""
          ENV_VARS_STRING+=" -e MAIL_USER=\"${{ inputs.MAIL_USER }}\""
          ENV_VARS_STRING+=" -e NODE_ENV=\"${{ inputs.NODE_ENV }}\""

          # Start the new Docker container using PM2
          echo "Starting new Docker container via PM2..."
          pm2 start "docker run --name "$DOCKER_CONTAINER_NAME" -p ${{ inputs.DOCKER_HOST_PORT }}:${{ inputs.DOCKER_CONTAINER_PORT }} $ENV_VARS_STRING -d $FULL_IMAGE" \
            --name "$DOCKER_CONTAINER_NAME" \
            --interpreter bash

          # Save PM2 process list for persistence across reboots
          echo "Saving PM2 process list..."
          pm2 save

          # Clean up old Docker images (optional but recommended)
          echo "Cleaning up old Docker images (pruning dangling images)..."
          docker image prune -f

          echo "Deployment complete!"
